[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2"
members = [
    "board_plugin",
    "tentative_title"
]

[workspace.dependencies]
bevy = { version = "0.13.2", features = ["wayland"] }
board-plugin = { path = "board_plugin" }
